---
name: 'generate-assets'
description: 'Generate app assets'

runs:
  using: 'composite'
  steps:
  - name: ci/cache-assets
    uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
    with:
      key: assets-v1-${{ hashFiles('assets/base/config.json') }}-${{ runner.arch }}
      path: dist
  - name: ci/genereate-assets
    shell: bash
    run: node ./scripts/generate-assets.js
  - name: ci/import-compass-icon
    shell: bash
    run: |
      COMPASS_ICONS="node_modules/@mattermost/compass-icons/font/compass-icons.ttf"
      cp "$COMPASS_ICONS" "assets/fonts/"
      cp "$COMPASS_ICONS" "android/app/src/main/assets/fonts"