---
name: 'fastlane-dependencies'
description: 'Install fastlane dependencies'

inputs:
  os:
    description: Name of the OS to generate dependencies for, to compartimentalize caching
    type: string
    required: true

runs:
  using: 'composite'
  steps:
  - name: ci/cache-fastlane-dependencies
    uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
    with:
      key: gems-v1-${{ inputs.os }}-${{ hashFiles('fastlane/Gemfile.lock') }}-${{ runner.arch }}
      path: fastlane/vendor/bundle
  - name: ci/get-fastlane-dependencies
    working-directory: fastlane
    shell: bash
    run: bundle install --path vendor/bundle