name: prepare-ios-build
description: Action to prepare environment for ios build

runs:
  using: composite
  steps:
    - name: ci/install-os-deps
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
      shell: bash
      run: |
        echo "::group::install-os-deps"
        brew install watchman
        echo "::endgroup::"

    - name: ci/prepare-mobile-build
      uses: ./.github/actions/prepare-mobile-build

    - name: ci/install-pods-dependencies
      shell: bash
      run: |
        echo "::group::install-pods-dependencies"
        ruby --version
        cd ios && pod cache clean --all && cd ..
        gem update cocoapods
        npm run ios-gems
        npm run pod-install-m1
        echo "::endgroup::"

    - name: ci/select-xcode-version
      shell: bash
      run: |
        echo "::group::install-pods-dependencies"
        sudo xcode-select --switch /Applications/Xcode_15.2.app
        echo "::endgroup::"
