name: prepare-mobile-build
description: Action to prepare environment for mobile build

runs:
  using: composite
  steps:
    - name: ci/setup-ruby
      env:
        RUBY_VERSION: "2.7.7"
      shell: bash
      run: |
        brew update
        brew install rbenv ruby-build
        rbenv install ${RUBY_VERSION}
        rbenv global ${RUBY_VERSION}
        # We cannot leverage 'rbenv init' as variables are reset at each step
        # https://github.com/rbenv/rbenv?tab=readme-ov-file#how-rbenv-hooks-into-your-shell
        echo "$HOME/.rbenv/shims" >> $GITHUB_PATH

    - name: ci/setup-fastlane-dependencies
      shell: bash
      run: |
        echo "::group::setup-fastlane-dependencies"
        bundle install
        echo "::endgroup::"
      working-directory: ./fastlane

    - name: ci/prepare-node-deps
      uses: ./.github/actions/prepare-node-deps
