---
name: 'pods-dependencies'
description: 'Get cocoapods dependencies'

runs:
  using: 'composite'
  steps:
  - name: ci/cache-pods-dependencies
    uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
    with:
      key: cocoapods-v1-${{ inputs.os }}-${{ hashFiles('ios/Podfile.lock') }}-${{ runner.arch }}
      path: |
        ios/Pods
        ~/.cocoapods
  - name: ci/get-pods-dependencies
    shell: bash
    run: |
      npm run ios-gems
      npm run pod-install