---
name: 'node-prepare'
description: 'Install node packages'

runs:
  using: 'composite'
  steps:
  - name: ci/cache-npm-dependencies
    uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
    with:
      key: npm-v1-${{ hashFiles('package-lock.json') }}
      path: node_modules
  - name: ci/install-npm-dependencies
    shell: bash
    run: |
      NODE_ENV=development npm ci --ignore-scripts
      node node_modules/\@sentry/cli/scripts/install.js
      node node_modules/react-native-webrtc/tools/downloadWebRTC.js
  - name: ci/patch-npm-dependencies
    shell: bash
    run: npx patch-package