---
name: build-ios
on:
  workflow_call:
    inputs:
      app_name:
        required: false
        type: string
      aws_bucket_name:
        required: false
        type: string
      aws_folder_name:
        required: false
        type: string
      aws_region:
        required: false
        type: string
      is_beta:
        required: false
        type: boolean
      build_for_release:
        required: false
        type: boolean
      is_pr:
        required: false
        type: boolean
      extension_app_identifier:
        required: false
        type: string
      branch_to_build:
        required: false
        type: string
        default: "main"
      build_artifact_name:
        required: true
        type: string
      build_type:
        required: false
        type: boolean
        # Valid values: signed, unsigned, simulator
        default: "signed"
      ios_app_group:
        required: false
        type: string
      ios_build_export_method:
        required: false
        type: string
      ios_icloud_container:
        required: false
        type: string
      main_app_identifier:
        required: false
        type: string
      match_app_identifier:
        required: false
        type: string
      match_type:
        required: false
        type: string
      node_options:
        required: false
        type: string
      notification_service_identifier:
        required: false
        type: string
      pilot_skip_waiting_for_build_processing:
        required: false
        type: boolean
        # To match the upstream default:
        # https://github.com/fastlane/fastlane/blob/be7d70a923fcde0655b8632de2088de9e3a743fe/pilot/lib/pilot/options.rb#L168
        default: false
      replace_assets:
        required: false
        type: boolean
        default: true
      sentry_enabled:
        required: false
        type: boolean
        default: false
      tag:
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: false
        type: string
      aws_secret_access_key:
        required: false
        type: string
      fastlane_team_id:
        required: false
        type: string
      gh_token:
        required: false
        type: string
      ios_api_issuer_id:
        required: false
        type: string
      ios_api_key:
        required: false
        type: string
      ios_api_key_id:
        required: false
        type: string
      match_git_url:
        required: false
        type: string
      match_password:
        required: false
        type: string
      mattermost_webhook_url:
        required: false
        type: string
      sentry_auth_token:
        required: false
        type: string
      sentry_dsn_ios:
        required: false
        type: string
      sentry_org:
        required: false
        type: string
      sentry_project_ios:
        required: false
        type: string

env:
  BRANCH_TO_BUILD: "${{ inputs.branch_to_build }}"
  APP_NAME: "${{ inputs.app_name }}"
  APP_SCHEME: "mattermost"
  AWS_ACCESS_KEY_ID: "${{ secrets.aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.aws_secret_access_key }}"
  AWS_BUCKET_NAME: "${{ inputs.aws_bucket_name }}"
  AWS_FOLDER_NAME: "${{ inputs.aws_folder_name }}"
  AWS_REGION: "${{ inputs.aws_region }}"
  BETA_BUILD: "${{ inputs.is_beta }}"
  BUILD_FOR_RELEASE: "${{ inputs.build_for_release }}"
  BUILD_PR: "${{ inputs.is_pr }}"
  EXTENSION_APP_IDENTIFIER: "${{ inputs.extension_app_identifier }}"
  FASTLANE_TEAM_ID: "${{ secrets.fastlane_team_id }}"
  GITHUB_TOKEN: "${{ secrets.gh_token }}"
  IOS_API_ISSUER_ID: "${{ secrets.ios_api_issuer_id }}"
  IOS_API_KEY: "${{ secrets.ios_api_key }}"
  IOS_API_KEY_ID: "${{ secrets.ios_api_key_id }}"
  IOS_APP_GROUP: "${{ inputs.ios_app_group }}"
  IOS_BUILD_EXPORT_METHOD: "${{ inputs.ios_build_export_method }}"
  IOS_ICLOUD_CONTAINER: "${{ inputs.ios_icloud_container }}"
  MAIN_APP_IDENTIFIER: "${{ inputs.main_app_identifier }}"
  MATCH_APP_IDENTIFIER: "${{ inputs.match_app_identifier }}"
  MATCH_GIT_URL: "${{ secrets.match_git_url }}"
  MATCH_PASSWORD: "${{ secrets.match_password }}"
  MATCH_READONLY: "true"
  MATCH_SHALLOW_CLONE: "true"
  MATCH_SKIP_DOCS: "true"
  MATCH_TYPE: "${{ inputs.match_type }}"
  MATTERMOST_WEBHOOK_URL: "${{ secrets.mattermost_webhook_url }}"
  NOTIFICATION_SERVICE_IDENTIFIER: "${{ inputs.notification_service_identifier }}"
  NODE_OPTIONS: "${{ inputs.node_options }}"
  PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING: "${{ inputs.pilot_skip_waiting_for_build_processing }}"
  REPLACE_ASSETS: "${{ inputs.replace_assets }}"
  SENTRY_AUTH_TOKEN: "${{ secrets.sentry_auth_token }}"
  SENTRY_DSN_IOS: "${{ secrets.sentry_dsn_ios }}"
  SENTRY_ENABLED: "${{ inputs.sentry_enabled }}"
  SENTRY_ORG: "${{ secrets.sentry_org }}"
  SENTRY_PROJECT_IOS: "${{ secrets.sentry_project_ios }}"
  SHOW_ONBOARDING: "true"
  SYNC_PROVISIONING_PROFILES: "true"
  TAG: "${{ inputs.tag }}"

jobs:
  build-ios:
    runs-on: macos-12
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: ci/node-prepare
      uses: ./.github/actions/node-prepare
    - name: ci/pods-dependencies
      uses: ./.github/actions/pods-dependencies
    - name: ci/generate-assets
      uses: ./.github/actions/generate-assets
    - name: ci/fastlane-dependencies
      uses: ./.github/actions/fastlane-dependencies
      with:
        os: ios
    # Build iOS app, method depends on the value of `build_type`
    - name: ci/build-ios-signed
      working-directory: ./fastlane
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install watchman
        export TERM=xterm && bundle exec fastlane ios build
      if: "${{ inputs.build_type == 'signed' }}"
    - name: ci/build-ios-unsigned
      working-directory: ./fastlane
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install watchman
        bundle exec fastlane ios unsigned
      if: "${{ inputs.build_type == 'unsigned' }}"
    - name: ci/build-ios-simulator
      working-directory: ./fastlane
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install watchman
        bundle exec fastlane ios simulator
      if: "${{ inputs.build_type == 'unsigned' }}"
    # Upload the build artifact, its path depends on the value of `build_type`
    - name: ci/upload-ios-buld
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: "${{ inputs.build_artifact_name }}"
        path: "*.ipa"
      if: "${{ inputs.build_type == 'signed' || inputs.build_type == 'unsigned' }}"
    - name: ci/upload-ios-buld-simulator
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: "${{ inputs.build_artifact_name }}"
        path: "Mattermost-simulator-x86_64.app.zip"
      if: "${{ inputs.build_type == 'simulator' }}"