---
name: test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.14.2-bullseye
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: ci/node-prepare
      uses: ./.github/actions/node-prepare
    - name: ci/generate-assets
      uses: ./.github/actions/generate-assets
    - name: ci/check-styles
      run: npm run check
    - name: ci/run-tests
      run: npm test
    - name: ci/check-i18n
      run: ./scripts/precommit/i18n.sh