---
name: "build-ios-simulator"
on:
  push:
    branches:
      # TODO: remove the `gha-` to match the current workflow again
      - "build-gha-*"
      - "build-ios-sim-gha-*"

jobs:
  build-ios-simulator:
    runs-on: macos-12
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: ci/output-ssh-private-key
        shell: bash
        run: |
          SSH_KEY_PATH=~/.ssh/id_ed25519
          if [ -n "${{ secrets.MM_MOBILE_PRIVATE_DEPLOY_KEY }}" ]; then
            mkdir -p ~/.ssh
            echo -e '${{ secrets.MM_MOBILE_PRIVATE_DEPLOY_KEY }}' > ${SSH_KEY_PATH}
            chmod 0600 ${SSH_KEY_PATH}
            ssh-keygen -y -f ${SSH_KEY_PATH} > ${SSH_KEY_PATH}.pub
          fi

      - name: ci/prepare-ios-build
        uses: ./.github/actios/prepare-ios-build

      - name: ci/build-ios-pr
        env:
          TAG: "${{ github.ref_name }}"
          GITHUB_TOKEN: "${{ secrets.MM_MOBILE_GITHUB_TOKEN }}"
        run: bundle exec fastlane ios simulator
        working-directory: ./fastlane

      - name: ci/upload-ios-pr-simulator
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ios-build-simulator-${{ github.run_id }}
          path: Mattermost-simulator-x86_64.app.zip
