---
name: "build-ios-pr"
# TODO: define these conditions afterwards
on:
  workflow_call:

jobs:
  build-ios-pr:
    uses: ./.github/workflows/.build-ios.yml
    with:
      branch_to_build: "${{ github.ref_name }}"
      build_artifact_name: "ios-build-${{ github.run_id }}"
      app_name: "Mattermost Beta"
      aws_bucket_name: "pr-builds.mattermost.com"
      aws_folder_name: "mattermost-mobile"
      aws_region: "us-east-1"
      is_beta: true
      build_for_release: true
      is_pr: true
      extension_app_identifier: "com.mattermost.rnbeta.MattermostShare"
      ios_app_group: "group.com.mattermost.rnbeta"
      ios_build_export_method: "ad-hoc"
      ios_icloud_container: "iCloud.com.mattermost.rnbeta"
      main_app_identifier: "com.mattermost.rnbeta"
      match_app_identifier: "com.mattermost.rnbeta.NotificationService,com.mattermost.rnbeta.MattermostShare,com.mattermost.rnbeta"
      match_type: "adhoc"
      notification_service_identifier: "com.mattermost.rnbeta.NotificationService"
      replace_assets: false
      sentry_enabled: false
    secrets:
      aws_access_key_id: "${{ secrets.MM_MOBILE_PR_AWS_ACCESS_KEY_ID }}"
      aws_secret_access_key: "${{ secrets.MM_MOBILE_PR_AWS_SECRET_ACCESS_KEY }}"
      fastlane_team_id : "${{ secrets.MM_MOBILE_FASTLANE_TEAM_ID }}"
      ios_api_issuer_id: "${{ secrets.MM_MOBILE_IOS_API_ISSUER_ID }}"
      ios_api_key: "${{ secrets.MM_MOBILE_IOS_API_KEY }}"
      ios_api_key_id: "${{ secrets.MM_MOBILE_IOS_API_KEY_ID }}"
      match_git_url: "${{ secrets.MM_MOBILE_MATCH_GIT_URL }}"
      match_password: "${{ secrets.MM_MOBILE_MATCH_PASSWORD }}"
      mattermost_webhook_url: "${{ secrets.MM_MOBILE_PR_MATTERMOST_WEBHOOK_URL }}"