---
name: build
on:
  push:
    branches:
  # TODO: uncomment the following after testing
  #    - main
  #pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.14.2-bullseye
    steps:
    - name: ci/checkout-repo
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: ci/node-prepare
      uses: ./.github/actions/node-prepare
    - name: ci/generate-assets
      uses: ./.github/actions/generate-assets
    - name: ci/check-styles
      run: npm run check
    - name: ci/run-tests
      run: npm test
    - name: ci/check-i18n
      run: ./scripts/precommit/i18n.sh
  #build-android-release:
  #  needs: [test]
  #build-android-beta:
  #deploy-android-beta:
  #build-ios-release:
  #deploy-ios-release:
  #build-ios-beta:
  #deploy-ios-beta:
  #build-android-pr:
  #build-ios-pr:
  #build-android-unsigned:
  #build-ios-unsigned:
  #build-ios-simulator:
  #github-release: