---
name: build-ios-beta

on:
  push:
    branches:
      # TODO: remove the `gha-` to match the current workflow again
      - build-gha-\d+$
      - build-gha-ios-\d+$
      - build-gha-ios-beta-\d+$

env:
  NODE_VERSION: 16.14.2
  TERM: xterm

jobs:
  build-ios-beta:
    runs-on: macos-12
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: ci/output-ssh-private-key
        shell: bash
        run: |
          SSH_KEY_PATH=~/.ssh/id_ed25519
          if [ -n "${{ secrets.MM_MOBILE_PRIVATE_DEPLOY_KEY }}" ]; then
            mkdir -p ~/.ssh
            echo -e '${{ secrets.MM_MOBILE_PRIVATE_DEPLOY_KEY }}' > ${SSH_KEY_PATH}
            chmod 0600 ${SSH_KEY_PATH}
            ssh-keygen -y -f ${SSH_KEY_PATH} > ${SSH_KEY_PATH}.pub
          fi

      - name: ci/prepare-ios-build
        uses: ./.github/actios/prepare-ios-build

      - name: ci/build-ios-beta
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.MM_MOBILE_BETA_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.MM_MOBILE_BETA_AWS_SECRET_ACCESS_KEY }}"
          FASTLANE_TEAM_ID: "${{ secrets.MM_MOBILE_FASTLANE_TEAM_ID }}"
          IOS_API_ISSUER_ID: "${{ secrets.MM_MOBILE_IOS_API_ISSUER_ID }}"
          IOS_API_KEY: "${{ secrets.MM_MOBILE_IOS_API_KEY }}"
          IOS_API_KEY_ID: "${{ secrets.MM_MOBILE_IOS_API_KEY_ID }}"
          MATCH_GIT_URL: "${{ secrets.MM_MOBILE_MATCH_GIT_URL }}"
          MATCH_PASSWORD: "${{ secrets.MM_MOBILE_MATCH_PASSWORD }}"
          MATTERMOST_WEBHOOK_URL: "${{ secrets.MM_MOBILE_BETA_MATTERMOST_WEBHOOK_URL }}"
          SENTRY_AUTH_TOKEN: "${{ secrets.MM_MOBILE_SENTRY_AUTH_TOKEN }}"
          SENTRY_DSN_IOS: "${{ secrets.MM_MOBILE_SENTRY_DSN_IOS }}"
          SENTRY_ORG: "${{ secrets.MM_MOBILE_SENTRY_ORG }}"
          SENTRY_PROJECT_IOS: "${{ secrets.MM_MOBILE_SENTRY_PROJECT_IOS }}"
        run: bundle exec fastlane ios build --env ios.beta
        working-directory: ./fastlane

      - name: ci/upload-ios-beta-build
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ios-build-beta-${{ github.run_id }}
          path: "*.ipa"
