---
name: "build-ios-beta"
on:
  push:
    branches:
    # TODO: remove the `gha-` to match the current workflow again
    - build-gha-\d+$
    - build-gha-ios-\d+$
    - build-gha-ios-beta-\d+$

jobs:
  build-ios-pr:
    uses: ./.github/workflows/.build-ios.yml
    with:
      build_artifact_name: "ios-build-beta-${{ github.run_id }}"
      build_type: "signed"
      app_name: "Mattermost Beta"
      app_scheme: "mattermost"
      aws_bucket_name: "releases.mattermost.com"
      aws_folder_name: "mattermost-mobile-beta"
      aws_region: "us-east-1"
      beta_build: "true"
      build_for_release: "true"
      extension_app_identifier: "com.mattermost.rnbeta.MattermostShare"
      ios_app_group: "group.com.mattermost.rnbeta"
      ios_build_export_method: "app-store"
      ios_icloud_container: "iCloud.com.mattermost.rnbeta"
      main_app_identifier: "com.mattermost.rnbeta"
      match_app_identifier: "com.mattermost.rnbeta.NotificationService,com.mattermost.rnbeta.MattermostShare,com.mattermost.rnbeta"
      match_readonly: "true"
      match_shallow_clone: "true"
      match_skip_docs: "true"
      match_type: "appstore"
      notification_service_identifier: "com.mattermost.rnbeta.NotificationService"
      pilot_skip_waiting_for_build_processing: "true"
      replace_assets: "false"
      sentry_enabled: "true"
      show_onboarding: "true"
      sync_provisioning_profiles: "true"
    secrets:
      aws_access_key_id: "${{ secrets.MM_MOBILE_BETA_AWS_ACCESS_KEY_ID }}"
      aws_secret_access_key: "${{ secrets.MM_MOBILE_BETA_AWS_SECRET_ACCESS_KEY }}"
      fastlane_team_id : "${{ secrets.MM_MOBILE_FASTLANE_TEAM_ID }}"
      ios_api_issuer_id: "${{ secrets.MM_MOBILE_IOS_API_ISSUER_ID }}"
      ios_api_key: "${{ secrets.MM_MOBILE_IOS_API_KEY }}"
      ios_api_key_id: "${{ secrets.MM_MOBILE_IOS_API_KEY_ID }}"
      match_git_url: "${{ secrets.MM_MOBILE_MATCH_GIT_URL }}"
      match_password: "${{ secrets.MM_MOBILE_MATCH_PASSWORD }}"
      mattermost_webhook_url: "${{ secrets.MM_MOBILE_BETA_MATTERMOST_WEBHOOK_URL }}"
      private_deploy_key: "${{ secrets.MM_MOBILE_PRIVATE_DEPLOY_KEY }}"
      sentry_auth_token: "${{ secrets.MM_MOBILE_SENTRY_AUTH_TOKEN }}"
      sentry_dsn_ios: "${{ secrets.MM_MOBILE_SENTRY_DSN_IOS }}"
      sentry_org: "${{ secrets.MM_MOBILE_SENTRY_ORG }}"
      sentry_project_ios: "${{ secrets.MM_MOBILE_SENTRY_PROJECT_IOS }}"
  #deploy-to-store:
  #  uses: ./.github/workflows/.deploy-to-store.yml
  #  with:
  #    build_artifact_name: "ios-build-beta-${{ github.run_id }}"
  #    os: 'ios'
  #  needs: [build-ios-pr]