name: Detox E2E Tests

on:
  push:
    branches:
      - 'test-template'

  workflow_dispatch:
    inputs:
      ios_version:
        description: 'Enter iOS version'
        required: false
        default: "iOS 17.4"
      device_name:
        description: 'Enter iOS Device Name'
        required: false
        default: "iPhone 15 Pro"
      commit_sha:
        type: string
        required: false

env:
  IOS_VERSION: ${{ github.event.inputs.ios_version }}
  DEVICE_NAME: ${{ github.event.inputs.device_name }}

jobs:
  run-ios-tests:
    name: Trigger iOS Detox Mobile Tests
    uses: ./.github/workflows/e2e-detox-ci-template.yml
    with:
      run-ios-tests: true
      run-android-tests: false
      commit_sha: "${{ inputs.commit_sha || github.sha }}"
      status_check_context: "Detox iOS Mobile Tests"
    secrets: inherit

