name: Detox E2E Tests

on:
  push:
    branches:
      - 'test-template'

  workflow_dispatch:
    inputs:
      commit_sha:
        type: string
        required: false

jobs:
  run-ios-tests:
    name: Mobile iOS Detox Tests
    uses: ./.github/workflows/e2e-detox-ci-template.yml
    with:
      run-ios-tests: true
      run-android-tests: false
      commit_sha: "${{ inputs.commit_sha || github.sha }}"
      status_check_context: "Mobile iOS Detox Tests"
    secrets: inherit

