name: Detox E2E Tests

on:
  pull_request:
    branches:
      - main
      - ios_detox_job
    types:
      - labeled
      - opened
  push:
    branches:
      - 'release-*'
      - 'test-template'
  schedule:
    - cron: '0 0 * * *'

  # workflow_dispatch:
  #   inputs:
  #     ios_version:
  #       description: 'Enter iOS version'
  #       required: false
  #       default: "iOS 17.4"
  #     device_name:
  #       description: 'Enter iOS Device Name'
  #       required: false
  #       default: "iPhone 15 Pro"

jobs:

  run-ios-tests:
    uses: ./.github/workflows/e2e-detox-ci-template.yml
    with:
      run-ios-tests: true
      run-android-tests: false
