name: Detox E2E Tests

on:
  push:
    branches:
      - 'test-template'

  workflow_dispatch:
    inputs:
      ios_version:
        description: 'Enter iOS version'
        required: false
        default: "iOS 17.4"
      device_name:
        description: 'Enter iOS Device Name'
        required: false
        default: "iPhone 15 Pro"

jobs:
  run-ios-tests:
    uses: ./.github/workflows/e2e-detox-ci-template.yml
    with:
      run-ios-tests: true
      run-android-tests: false
    secrets: inherit
