name: Detox E2E Tests

on:
  pull_request:
    branches:
      - main
      - ios_detox_job
    types:
      - labeled
      - opened
  push:
    branches:
      - 'release-*'
      - 'test-template'
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

  workflow_dispatch:
    inputs:
      ios_version:
        description: 'Enter iOS version'
        required: false
        default: "iOS 17.4"
      device_name:
        description: 'Enter Device Name'
        required: false
        default: "iPhone 15 Pro"

jobs:

  run-ios-tests:
    if: |
      contains(github.event.pull_request.labels.*.name, 'E2E iOS tests for PR') ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/test-template')) ||
      (github.event_name == 'schedule')
    uses: ./.github/workflows/e2e-detox-ci-template.yml
    with:
      run-ios-tests: true
      run-android-tests: false
